### ISSUE TITLE
Unclear segmentation result

### ISSUE THREAD

**Issue by GMFranceschini** [LukasBurger/MethylSeekR#3]
Good morning,
I am using MethylSeekR to define PMDs in a cancer cell line using WGBS data, thank you for developing the tool.

However, the result of the segmentation is somehow puzzling to me: I observe large chunks with intermediate methylation that are not captured as PMDs, but as UMRs. I know that the presence of large UMRs has been reported, but in some cases, like the one I report below, it almost seems like a slight change in the average methylation level turns a PMD into a large UMR. 
Am I missing something?

I hope this is the right place to ask

![image](https://user-images.githubusercontent.com/26085801/151388590-46a9d876-cc3a-421d-995e-51f91cd81b5c.png)

**Comment by LukasBurger** [comment]
Hi, thanks for using MethylSeekR. Yes, this is a problem that has come up previously. At the time MethylSeekR was developed, there were only few whole-genome bisulfite datasets available and PMDs were characterized as stretches of CpGs that had a roughly uniform methylation distribution (between 0 and 100% methyalted) in these few available data-sets, so MethylSeekR was designed to detect this feature. However, it turns out that these PMDs can have even further reduced levels in other cell types such that the distribution of methylation levels is not uniform any more but biased towards zero. These regions cannot be detected by MethylSeekR and I think this is what is happening here. One could also question the use of the term "partially methylated" if most CpGs have methylation levels close to zero. I think you will have to go with some other method for segmenting the regions you are interested in.

**Comment by GMFranceschini** [comment]
Thank you for your precise answer, Lukas. I understand the issue. 
Do you think this could be fixed somehow, or are those low levels of methylation incompatible with how methylSeekR works? 
I could try to look into that if you think there might be room for a solution. 

In any case, may I ask you which tool you would recommend for this task given your experience?

**Comment by LukasBurger** [comment]
Hi, I think there is no easy fix for this problem within the MethylSeekR framework. However, I think it should be possible to calculate average methylation levels in a sliding window along the genome and use the average methylation in the window as a read-out for segmentation (the "PMDs" should have significantly lower methylation). You may have to play a bit with different window sizes to get to a decent result (or even use a fixed number of CpGs per window instead of a fixed number of nucleotides), but in principle I feel this should work. Unfortunately, I am not familiar with state-of-the-art tools for this problem, haven't worked on this for quite a while now. Hope this helps.

**Comment by GMFranceschini** [comment]
Thank you, Lukas, you have been indeed very helpful. Closing the issue!
